# profiles.yml

default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "gs-arial"
      dataset: transformed
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEYFILE_PATH', 'gcp-credentials.json') }}"
      timeout_seconds: 300
      priority: interactive