Arial:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "gs-arial"
      dataset: transformed
      threads: 4
      keyfile: "{{ env_var('DBT_SA_KEY', '../../service accounts/dbt-service-account.json') }}"
      timeout_seconds: 300
      priority: interactive
